export const MockFilterOptions = [
  'Companies',
  'Individuals',
  'Aircraft',
  'Crypto wallets'
]

export const mockSortOptions = [
  'Oldest updated',
  'Bookmarked',
  'Not bookmarked yet'
]

export const mockMetaTags = [
  'Ukraine',
  'Draeger',
  'Oliver Barnard Draeger',
  'PBG-Project Building Generals',
  'Michael John',
  'Mark Lindon'
]

export const mockSpecialFilterTags = [
  'Crime',
  'Warmongers',
  'Bribetakers',
  'Spy',
  'Theft',
  'War crimes',
  'Terrorism',
  'Criminal leadership',
  'Debarred entity',
  'Judge',
  'Financial crime',
  'Intergovernmental Organization',
  'Offshore',
  'Person of interest',
  'Political party mock',
  'Political party mock',
  'Political party mock',
  'Political party mock',
  'Political party mock',
  'Political party mock',
  'Political party mock',
  'Political party mock'
]

export const mockCountryFilter = [
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'AndorrA',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  'Cote D\'Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic Of',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Democratic People\'S Republic of',
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'S Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia, The Former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory, Occupied',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'RWANDA',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]

export const mockSearchHistory = [
  {
    name: 'Nora Frey Draeger',
    type: 'Companies',
    number: '321',
    time: '11:30 AM',
    date: '2023-07-25',
    address: 'Flat 9, 112 Belgrave Road, London, SW1V 2BL',
    birthdate: 'Setember 1978',
    nationality: 'British',
    tags: [
      'Bank',
      'Political party',
      'Financial crim',
      'Person of interest',
      'Interes1',
      'Interes2',
      'Interes3',
      'Interes4',
      'Interes5'
    ]
  },
  {
    name: 'Donald Trump',
    type: 'Person',
    number: '114',
    time: '11:30 AM',
    date: '2023-07-25',
    tags: ['Bank']
  },
  {
    name: 'Diclekent Mahallesi',
    type: 'Address',
    number: '226',
    time: '11:30 AM',
    date: '2023-07-25',
    tags: ['Bank']
  },
  {
    name: '0x776198CCF446DFa16832473575327387353',
    type: 'Cryptocurrency Wallet',
    number: '39',
    time: '11:30 AM',
    date: '2023-07-25',
    tags: ['Bank']
  },
  {
    name: 'Van Helsing',
    type: 'Companies',
    number: '12',
    time: '11:30 AM',
    date: '2023-07-25',
    tags: ['Bank']
  },
  {
    name: '0x776198CCF446DFa1683453546456456',
    type: 'Cryptocurrency Wallet',
    number: '64',
    time: '11:30 AM',
    date: '2023-07-24',
    tags: ['Bank']
  },
  {
    name: 'Jack Sanders',
    type: 'Individuals',
    number: '92',
    time: '11:30 AM',
    date: '2023-07-24',
    tags: ['Bank']
  },
  {
    name: 'Tony Stark',
    type: 'Companies',
    number: '57',
    time: '11:30 AM',
    date: '2023-07-24',
    tags: ['Bank']
  },
  {
    name: 'Thor Odinson',
    type: 'Individuals',
    number: '18',
    time: '11:30 AM',
    date: '2023-07-24',
    tags: ['Bank']
  },
  {
    name: 'Tom Jonson',
    type: 'Aircraft',
    number: '179',
    time: '11:30 AM',
    date: '2023-07-24',
    tags: ['Bank']
  }
]

export const mockButtonCategory = ['Address', 'Vessels', 'Bank Account', 'Company, Organization', 'Crypto Wallet', 'Person', 'Security']
